name: build-mod
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:

permissions: read-all

jobs:
  build-the-mod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Set output file name
        id: determine_filename
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "output_file_name=SCE_Release_${{ github.event.release.tag_name }}.json" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "output_file_name=SCE_PR_${{ github.head_ref }}.json" >> $GITHUB_ENV
          else
            echo "output_file_name=SCE_output.json" >> $GITHUB_ENV
        shell: bash

      - uses: argonui/TTSModManager.action@v1.1.0
        with:
          output-file: ${{ env.output_file_name }}
